/**
 * QuickTake — AI-generated professor sentiment summary card.
 *
 * Displays the cached ReviewSummary data. The underlying LLM call is done
 * nightly via /api/cron/ai-summary; this component only renders cached data.
 */

interface QuickTakeProps {
  quickTake: string;
  workload: string | null;
  gradingDifficulty: string | null;
  teachingStyle: string | null;
  sentimentScore: number | null;
  reviewCount: number;
  lastUpdated: Date;
  modelUsed: string | null;
}

const sentimentLabel = (score: number | null) => {
  if (score === null) return null;
  if (score >= 0.8) return { label: "Very Positive", color: "#0f6b48" };
  if (score >= 0.6) return { label: "Positive", color: "#2e7d5e" };
  if (score >= 0.4) return { label: "Mixed", color: "#8a6000" };
  if (score >= 0.2) return { label: "Negative", color: "#c0392b" };
  return { label: "Very Negative", color: "#96281b" };
};

export default function QuickTake({
  quickTake,
  workload,
  gradingDifficulty,
  teachingStyle,
  sentimentScore,
  reviewCount,
  lastUpdated,
  modelUsed
}: QuickTakeProps) {
  const sentiment = sentimentLabel(sentimentScore);

  return (
    <div className="quick-take">
      <div className="quick-take__header">
        <div className="quick-take__title-row">
          <span className="quick-take__icon" aria-hidden="true">✦</span>
          <h2 className="quick-take__title">AI Quick Take</h2>
          {sentiment && (
            <span
              className="quick-take__sentiment"
              style={{ color: sentiment.color, borderColor: sentiment.color }}
            >
              {sentiment.label}
            </span>
          )}
        </div>
        <p className="quick-take__meta">
          Based on {reviewCount} review{reviewCount !== 1 ? "s" : ""} ·{" "}
          Updated{" "}
          {new Date(lastUpdated).toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
            year: "numeric"
          })}
        </p>
      </div>

      <p className="quick-take__body">{quickTake}</p>

      {(workload || gradingDifficulty || teachingStyle) && (
        <div className="quick-take__pillars">
          {workload && (
            <div className="quick-take__pillar">
              <span className="quick-take__pillar-label">Workload</span>
              <span className="quick-take__pillar-value">{workload}</span>
            </div>
          )}
          {gradingDifficulty && (
            <div className="quick-take__pillar">
              <span className="quick-take__pillar-label">Grading</span>
              <span className="quick-take__pillar-value">{gradingDifficulty}</span>
            </div>
          )}
          {teachingStyle && (
            <div className="quick-take__pillar">
              <span className="quick-take__pillar-label">Teaching Style</span>
              <span className="quick-take__pillar-value">{teachingStyle}</span>
            </div>
          )}
        </div>
      )}

      <p className="quick-take__disclaimer">
        Generated by AI ({modelUsed ?? "AI model"}) from student reviews. Not an official rating.
      </p>
    </div>
  );
}
